AllCops:
  NewCops: enable
  AutoCorrect: true
  Include:
    - 'lib/**/*.rb'
    - 'modules/**/*.rb'
  TargetRubyVersion: 2.7.1

Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false
